{
 "title": "Power Utilisation & Solar Array",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Energy Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Watts (In/Out)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "PV Input",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_pv_in_watts" }
       ]
      },
      {
       "alias": "Inverter Output",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "W",
       "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'voltronic_load_watt') AND $timeFilter GROUP BY time($interval) fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_load_watt" }
       ]
      },
      {
       "alias": "Grid Input",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "shellyem_c7face_channel_1_power"
        }
       ]
      },
      {
       "alias": "Battey Output",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "* 48  " ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "voltronic_battery_discharge_current"
        }
       ]
      }
     ]
    },
    {
     "title": "Battery Bank Charge/Discharge",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Charge Current",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "voltronic_battery_charge_current"
        }
       ]
      },
      {
       "alias": "Discharge Current",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "voltronic_battery_discharge_current"
        }
       ]
      }
     ]
    },
    {
     "title": "PV Input Current",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "PV Watts (W)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_pv_in_watts" }
       ]
      },
      {
       "alias": "PV Current (A)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_pv_in_current" }
       ]
      },
      {
       "alias": "PV Volts (V)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_pv_in_voltage" }
       ]
      }
     ]
    },
    {
     "title": "Battery Bank Voltage (V)",
     "type": "graph",
     "description": "Assumes 50% Discharge maximum on battery bank - To give approx. 3000 Cycles (8Years on bank)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_battery_voltage" }
       ]
      }
     ]
    },
    {
     "title": "Battery Array Capacity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_battery_capacity" }
       ]
      }
     ]
    },
    {
     "title": "Grid Voltage Fluctuations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "alias": "AC Grid Volts",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_ac_grid_voltage" }
       ]
      }
     ]
    },
    {
     "title": "AC Inverter Volts Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "alias": "AC Inverter Volts",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_ac_out_voltage" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Dials - kWh & Costs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Eskom kWh Consumed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Eskom - Total KWH",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "shellyem_c7face_channel_1_energy"
        }
       ]
      }
     ]
    },
    {
     "title": "Total Inverter kWh Consumed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "PV - Total kWh",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "shellyem_c7face_channel_2_energy"
        }
       ]
      }
     ]
    },
    {
     "title": "Inverter kWh Output",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 60 / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_load_watt" }
       ]
      }
     ]
    },
    {
     "title": "Total Inverter kWh (Time Series)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "PV - Total kWh",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 120" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "shellyem_c7face_channel_1_power"
        }
       ]
      }
     ]
    },
    {
     "title": "Shelly Inverter kWh (Time Series)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "PV - Total kWh",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 500" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "shellyem_c7face_channel_2_power"
        }
       ]
      }
     ]
    },
    {
     "title": "Eskom  (Display Period @ R2.2 / p/kWh)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyZAR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 60 / 86.4 * 2.20" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "shellyem_c7face_channel_1_power"
        }
       ]
      }
     ]
    },
    {
     "title": "Inverter (Display Period @ R2.2 / p/kWh)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyZAR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "W",
       "query": "SELECT sum(\"value\")  / 60 * 2.20 FROM \"W\" WHERE (\"entity_id\" = 'shellyem_c7face_channel_2_power') AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 60 / 86.4 * 2.20" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "shellyem_c7face_channel_2_power"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Dials - Inverter Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load (%)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_load_pct" }
       ]
      }
     ]
    },
    {
     "title": "PV in (V)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_pv_in_voltage" }
       ]
      }
     ]
    },
    {
     "title": "Battery Charge (A)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "voltronic_battery_charge_current"
        }
       ]
      }
     ]
    },
    {
     "title": "Battery Discharge (A)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "voltronic_battery_discharge_current"
        }
       ]
      }
     ]
    },
    {
     "title": "SCC (V)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_scc_voltage" }
       ]
      }
     ]
    },
    {
     "title": "Grid in (V)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_ac_grid_voltage" }
       ]
      }
     ]
    },
    {
     "title": "Inverter Out (V)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_ac_out_voltage" }
       ]
      }
     ]
    },
    {
     "title": "Setting Grid Charge (A)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "voltronic_max_grid_charge_current"
        }
       ]
      }
     ]
    },
    {
     "title": "Inverter Out (W)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_load_watt" }
       ]
      }
     ]
    },
    {
     "title": "PV in (A)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_pv_in_current" }
       ]
      }
     ]
    },
    {
     "title": "Battery Recharge (V)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "voltronic_battery_recharge_voltage"
        }
       ]
      }
     ]
    },
    {
     "title": "Grid AC (Hz)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Hz",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_ac_grid_frequency" }
       ]
      }
     ]
    },
    {
     "title": "Inverter AC Out (Hz)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Hz",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_ac_out_frequency" }
       ]
      }
     ]
    },
    {
     "title": "Setting PV Charge (A)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "A",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_max_charge_current" }
       ]
      }
     ]
    },
    {
     "title": "Eskom in  (W)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "shellyem_c7face_channel_1_power"
        }
       ]
      }
     ]
    },
    {
     "title": "PV in  (W)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "W",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_pv_in_watts" }
       ]
      }
     ]
    },
    {
     "title": "Battery (V)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "V",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "voltronic_battery_voltage" }
       ]
      }
     ]
    }
   ]
  }
 ]
}