title: Home Dashboard
views:
  - title: Switches
    path: switches
    icon: 'mdi:home-automation'
    badges: []
    cards:
      - type: entities
        entities:
          - switch.waterpomp
        title: RotoTank
        show_header_toggle: false
        state_color: true
        header:
          type: buttons
          entities: []
      - type: weather-forecast
        entity: weather.home
        show_forecast: false
      - type: entities
        entities:
          - sun.sun
        title: Sun
  - badges: []
    cards:
      - cards:
          - entities:
              - entity: sensor.voltronic_battery_capacity
                name: Battey SOC
                icon: 'mdi:battery'
                type: sensor
              - entity: sensor.voltronic_load_watt
                name: Inv Load
                icon: 'mdi:current-ac'
                type: sensor
              - entity: sensor.voltronic_pv_in_voltage
                name: PV Voltage (V)
                icon: 'mdi:sine-wave'
                type: sensor
              - entity: sensor.voltronic_pv_in_watts
                name: PV Watts (W)
                icon: 'mdi:battery-charging-70'
                type: sensor
              - entity: sensor.voltronic_pv_in_current
                name: PV Amps (A)
                icon: 'mdi:current-dc'
                type: sensor
            type: glance
          - entities:
              - entity: sensor.voltronic_load_watt
                name: Inverter Output Load
            type: history-graph
          - entities:
              - entity: sensor.voltronic_ac_grid_frequency
                icon: 'mdi:current-ac'
                name: Grid Frequency
              - entity: sensor.voltronic_ac_grid_voltage
                icon: 'mdi:power-plug'
                name: Grid Voltage
              - entity: sensor.voltronic_ac_out_frequency
                icon: 'mdi:current-ac'
                name: Output Freq
              - entity: sensor.voltronic_ac_out_voltage
                icon: 'mdi:power-plug'
                name: Output Voltage
            type: glance
          - entity: sensor.voltronic_heatsink_temperature
            name: Heatsink Temperature
            type: sensor
            icon: 'mdi:temperature-celsius'
        show_header_toggle: false
        title: System Overview
        type: 'custom:vertical-stack-in-card'
      - cards:
          - type: conditional
            conditions:
              - entity: sensor.voltronic_inverter_mode
                state: '1'
            card:
              type: picture
              image: /local/inverter-modes/1.png
          - type: conditional
            conditions:
              - entity: sensor.voltronic_inverter_mode
                state: '2'
            card:
              type: picture
              image: /local/inverter-modes/2.png
          - type: conditional
            conditions:
              - entity: sensor.voltronic_inverter_mode
                state: '3'
            card:
              type: picture
              image: /local/inverter-modes/3.png
          - type: conditional
            conditions:
              - entity: sensor.voltronic_inverter_mode
                state: '4'
            card:
              type: picture
              image: /local/inverter-modes/4.png
          - type: conditional
            conditions:
              - entity: sensor.voltronic_inverter_mode
                state: '5'
            card:
              type: picture
              image: /local/inverter-modes/5.png
          - type: conditional
            conditions:
              - entity: sensor.voltronic_inverter_mode
                state: '6'
            card:
              type: picture
              image: /local/inverter-modes/6.png
          - content: |
              ---
            type: markdown
          - type: entities
            entities:
              - entity: input_select.solar_output_source_priority
                icon: 'mdi:battery'
              - entity: input_select.solar_charger_priority
                icon: 'mdi:format-list-numbered'
              - entity: automation.auto_switch_to_solar_only_charging_at_sunrise
              - entity: automation.switch_to_battery_preferred_output_at_sundown
              - entity: automation.solar_switch_to_utility_21_soc
        show_header_toggle: false
        title: System Settings
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - color_stops:
                  '40': '#00dc10'
                  '60': '#ff0000'
                  '80': '#ffe400'
                entity: sensor.voltronic_load_pct
                font_style:
                  font-size: 1.5em
                gradient: true
                name: System Load (%)
                stroke_width: 10
                type: 'custom:circle-sensor-card'
              - color_stops:
                  '50': '#ff0000'
                  '75': '#ffe400'
                  '100': '#00dc10'
                entity: sensor.voltronic_battery_capacity
                font_style:
                  font-size: 1.5em
                gradient: true
                name: Battery Capacity
                stroke_width: 10
                type: 'custom:circle-sensor-card'
            type: horizontal-stack
          - entities:
              - entity: sensor.voltronic_battery_charge_current
                name: Battery Charge Current (A)
              - entity: sensor.voltronic_battery_discharge_current
                name: Battery Discharge Current (A)
            type: history-graph
          - entities:
              - entity: sensor.voltronic_battery_float_voltage
                icon: 'mdi:battery-charging'
                name: Float Point
              - entity: sensor.voltronic_battery_discharge_current
                icon: 'mdi:battery-negative'
                name: Discharge (A)
              - entity: sensor.voltronic_battery_charge_current
                icon: 'mdi:battery-plus'
                name: Change (A)
              - entity: sensor.voltronic_battery_under_voltage
                icon: 'mdi:battery-charging-wireless-outline'
                name: Critical Cutoff
            type: glance
          - entity: sensor.voltronic_battery_voltage
            name: Battery Voltage (V)
            type: sensor
        show_header_toggle: false
        title: Battery Overview
        type: 'custom:vertical-stack-in-card'
    icon: 'mdi:grid'
    title: Solar Configuration
  - icon: 'mdi:power-plug'
    title: Power
    path: power
    panel: false
    badges: []
    cards:
      - entities:
          - sensor.hourly_solar_energy
        hour24: true
        hours_to_show: 24
        name: Solar Hourly Energy Meter
        points_per_hour: 1
        show:
          graph: bar
        type: 'custom:mini-graph-card'
      - type: 'custom:mini-graph-card'
        entities:
          - entity: sensor.daily_solar_energy
        name: Solar Daily Energy Meter
        hours_to_show: 168
        aggregate_func: max
        group_by: date
        show:
          graph: bar
      - type: entities
        entities:
          - sensor.hourly_solar_energy
          - sensor.daily_solar_energy
          - sensor.weekly_solar_energy
          - sensor.monthly_solar_energy
          - sensor.yearly_solar_energy
        title: Solar Energy Use
      - type: entities
        entities:
          - sensor.hourly_eskom_energy
          - sensor.daily_eskom_energy
          - sensor.weekly_eskom_energy
          - sensor.monthly_eskom_energy
          - sensor.yearly_eskom_energy
        title: Eskom Energy Use
      - entities:
          - sensor.hourly_eskom_energy
        hour24: true
        hours_to_show: 24
        name: Eskom Hourly Energy Meter
        points_per_hour: 1
        show:
          graph: bar
        type: 'custom:mini-graph-card'
      - type: 'custom:mini-graph-card'
        entities:
          - entity: sensor.daily_eskom_energy
        name: Eskom Daily Energy Meter
        hours_to_show: 168
        aggregate_func: max
        group_by: date
        show:
          graph: bar
      - type: entities
        entities:
          - binary_sensor.shellyem_c7face_overpowering
          - sensor.shellyem_c7face_channel_1_power
          - sensor.shellyem_c7face_channel_1_energy
          - sensor.shellyem_c7face_channel_1_energy_returned
          - sensor.shellyem_c7face_channel_1_voltage
          - sensor.shellyem_c7face_channel_2_power
          - sensor.shellyem_c7face_channel_2_energy
          - sensor.shellyem_c7face_channel_2_energy_returned
          - sensor.shellyem_c7face_channel_2_voltage
          - switch.shellyem_c7face
        title: Garage
  - title: Grafana Analytics
    path: grafana-analytics
    icon: 'mdi:home-analytics'
    panel: true
    badges: []
    cards:
      - type: iframe
        url: >-
          https://[redacted]/d/3D38IbwGz/power-utilisation-and-solar-array?viewPanel=5&orgId=1&refresh=1m&from=1616498235885&to=1616519835885
        aspect_ratio: 100%
        title: Power Utilization
